#  ARRAY CREATION #

In [20]:
import numpy as np
import pprint


In [27]:
a =  np.array([(2,3,4),(4,5,0),(1,8,3)])

# min #

In [22]:
a.min()

0

# max #

In [8]:
a.max()

6

# mean #

In [9]:
a.mean()

3.3333333333333335

# argmin #

In [94]:
np.argmin(a)

5

In [34]:
np.argmin(a,axis=1)

array([0, 2, 0])

# linear alg #


In [41]:
p = np.array([[1,2],[3,4]])
q = np.array([5,7])
x = np.linalg.solve(p, q)
x

array([-3.,  4.])

In [43]:
np.allclose(np.dot(p,x),q)

True

# flatten #

In [47]:
a.flatten(order='F')

array([2, 4, 1, 3, 5, 8, 4, 0, 3])

In [48]:
a.flatten(order='C')

array([2, 3, 4, 4, 5, 0, 1, 8, 3])

# ravel #


In [49]:
a.ravel()

array([2, 3, 4, 4, 5, 0, 1, 8, 3])

# dot product #

In [50]:
np.dot(p,q)

array([19, 43])

In [51]:
a = [[1, 0], [0, 1]] 
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

# element wise multiplication #

In [54]:
np.array([[1,0],[0,1]])*np.array([[4,1],[2,2]])

array([[4, 0],
       [0, 2]])

# arange followed by reshape #

In [12]:
z = np.arange(6).reshape(3,2)
z

array([[0, 1],
       [2, 3],
       [4, 5]])

# identity/eye #

In [14]:
np.eye(3,k=0)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

# sum #

In [15]:
b=np.array([[1,4,3],[2,4,5],[2,3,9]])

In [5]:
np.sum(b)
np.sum(b,axis=1)

array([ 8, 11,  8])

# diag #

In [17]:
np.diag(b,k=0)


array([1, 4, 9])

# tril/triu #

In [28]:
np.triu([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [29]:
np.tril([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])